on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: primefootballregistry.azurecr.io
        username: ${{ secrets.acr_primefootballregistry_username }}
        password: ${{ secrets.acr_primefootballregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/post-service" -f  "post-service/Dockerfile" -t primefootballregistry.azurecr.io/primefootballcluster:${{ github.sha }} --label dockerfile-path=post-service/Dockerfile
        docker push primefootballregistry.azurecr.io/primefootballcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_primefootballcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep prime-football-cluster | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace prime-football-cluster`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: prime-football-cluster
        container-registry-url: primefootballregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_primefootballregistry_username }}
        container-registry-password: ${{ secrets.acr_primefootballregistry_password }}
        secret-name: primefootbaldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: prime-football-cluster
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          primefootballregistry.azurecr.io/primefootballcluster:${{ github.sha }}
        imagepullsecrets: |
          primefootbaldockerauth
